# Generated by Django 5.2 on 2025-11-04 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=50, verbose_name="类别名称")),
                ("slug", models.SlugField(unique=True, verbose_name="类别网址")),
            ],
            options={
                "verbose_name": "类别",
                "verbose_name_plural": "类别",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="商品标题")),
                ("link", models.URLField(verbose_name="商品链接")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("image_url", models.URLField(verbose_name="图片链接")),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                (
                    "crawl_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上架时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodsapp.category",
                        verbose_name="商品类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "goods",
                "ordering": ["-crawl_time"],
            },
        ),
        migrations.CreateModel(
            name="GoodsDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="goods/main/%Y/%m/%d/",
                        verbose_name="主图",
                    ),
                ),
                (
                    "thumbnail_images_urls",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式存储缩略图URL列表",
                        verbose_name="缩略图URL列表",
                    ),
                ),
                (
                    "detail_images_urls",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式存储详情图URL列表",
                        verbose_name="详情图URL列表",
                    ),
                ),
                ("materials", models.TextField(blank=True, verbose_name="花材信息")),
                ("packaging", models.TextField(blank=True, verbose_name="包装信息")),
                ("scenarios", models.TextField(blank=True, verbose_name="适用场景")),
                ("meaning", models.TextField(blank=True, verbose_name="花语信息")),
                (
                    "specifications",
                    models.TextField(
                        blank=True, help_text="JSON格式存储规格信息", verbose_name="规格参数"
                    ),
                ),
                (
                    "list_title",
                    models.CharField(blank=True, max_length=500, verbose_name="列表标题"),
                ),
                (
                    "list_price",
                    models.CharField(blank=True, max_length=50, verbose_name="列表价格"),
                ),
                (
                    "list_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="goods/list/%Y/%m/%d/",
                        verbose_name="列表图片",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="源链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "goods",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="goodsapp.goods",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品详情",
                "verbose_name_plural": "商品详情",
                "db_table": "goods_detail",
            },
        ),
        migrations.AddIndex(
            model_name="goods",
            index=models.Index(
                fields=["category", "is_active"], name="goods_categor_6054bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goods",
            index=models.Index(fields=["price"], name="goods_price_d63715_idx"),
        ),
        migrations.AddIndex(
            model_name="goods",
            index=models.Index(fields=["created_at"], name="goods_created_3de311_idx"),
        ),
    ]
