# Generated by Django 5.2 on 2025-11-06 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goodsapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoodsDetail",
        ),
    ]
