# Generated by Django 5.2 on 2025-11-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodsapp", "0002_delete_goodsdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="stock",
            field=models.IntegerField(default=100, verbose_name="库存"),
        ),
    ]
