# Generated by Django 5.2 on 2025-11-13 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodsapp", "0004_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(verbose_name="卡片内容")),
                ("color", models.CharField(max_length=20, verbose_name="背景颜色")),
                ("border_color", models.CharField(max_length=20, verbose_name="边框颜色")),
                ("x", models.FloatField(verbose_name="X坐标")),
                ("y", models.FloatField(verbose_name="Y坐标")),
                ("dx", models.FloatField(verbose_name="X方向速度")),
                ("dy", models.FloatField(verbose_name="Y方向速度")),
                ("width", models.FloatField(verbose_name="宽度")),
                ("height", models.FloatField(verbose_name="高度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "漂流卡片",
                "verbose_name_plural": "漂流卡片",
                "db_table": "cards",
            },
        ),
    ]
