# Generated by Django 5.2 on 2025-11-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodsapp", "0005_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flower",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200, verbose_name="商品标题")),
                ("price", models.CharField(max_length=20, verbose_name="价格")),
                ("thumbnails", models.JSONField(default=list, verbose_name="缩略图")),
                ("description", models.TextField(verbose_name="商品描述")),
                ("materials", models.TextField(verbose_name="花材信息")),
                ("packaging", models.TextField(verbose_name="包装信息")),
                ("scenarios", models.TextField(verbose_name="适用场景")),
                ("meaning", models.TextField(verbose_name="花语")),
                ("crawl_time", models.DateTimeField(verbose_name="爬取时间")),
                ("list_title", models.CharField(max_length=300, verbose_name="列表标题")),
            ],
            options={
                "verbose_name": "花卉商品",
                "verbose_name_plural": "花卉商品",
                "db_table": "flowers",
            },
        ),
    ]
