"""
Django settings for flower project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取 SECRET_KEY（docker-compose.yml 中配置）
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# 从环境变量读取 DEBUG（容器中为 False）
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# 从环境变量读取 ALLOWED_HOSTS
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# CSRF 信任源（添加你的公网IP/域名）
CSRF_TRUSTED_ORIGINS = [
    f'http://{host}' for host in ALLOWED_HOSTS if host
] + [
    f'https://{host}' for host in ALLOWED_HOSTS if host
]

if not DEBUG:  # 仅生产环境（容器中 DEBUG=False）启用
    # 信任 Nginx 转发的 HTTPS 标识
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # 可选：强制所有 HTTP 请求跳转到 HTTPS（提升安全性）
    # SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "userapp",
    "goodsapp",
    "cartapp",
    "orderapp",
    "searchapp",
    'rest_framework',          # 之前添加的 DRF（用于构建 API）
    'corsheaders',             # 跨域插件
    'admin_api',               # 之前新建的后台 API 应用（处理后台请求）
    'rest_framework.authtoken',  # 令牌认证
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 跨域中间件
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "flower.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "flower.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库配置（从环境变量读取 DATABASE_URL）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE', 'flower'),
        'USER': 'root',
        'PASSWORD': os.getenv('MYSQL_ROOT_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),  # db 是 docker-compose 中 MySQL 服务的名称
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static_collected")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    ]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 文件上传设置
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'userapp.User'

# 确保认证后端正确配置
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

#邮箱配置
MAIL_FROM_ADDR = 'jycicy412@163.com'
MAIL_PASSWORD = 'KKTBH8YPDDX7LtSu'
MAIL_SMTP_SERVER = 'smtp.163.com'
MAIL_INTEREAL = 60    # 60秒内不能重复发送邮件
VCODE_EXPIRE = 60*5   # 验证码有效时间


# 支付宝沙箱
ALIPAY_CONFIG = {
    'appid': '9021000155640011',
    'app_notify_url': 'https://b888e2925deb.ngrok-free.app/order/notify/',  # 异步通知回调地址
    'app_private_key_string': '''-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAiZ7j/RRPxSjKJHjRnerlBU8XTVmuYbJ8bV4EvqJyc1Bx4SsAp3IfQTd56GxjoxBQ9zwyFhh1onlrmyAkWecB1taaKzP4bBkiCs9dStGlQ0kib0yrjQyg2jSOrDHOhM6aewofI3wqjYpNjEhXHmDYKJjDP68nkGMOtTPRfr5wk0H/X9WTb9x2k8opUow5gaKNy8T/8Airp7fzzIrjH+91/AdPKgOlvBeXiWSd288ZChYOXRAJcrG+uEk2ycaCz1yZT+ldJ47Woq0ACRVibYhFD2m4KntcMFcWEln298tZBGxM3VtHJE+XlHN/5cp/XwhKbQtmHRfzbgmdKO4H6sKzeQIDAQABAoIBAAJHRCUDehKci0QxT98abXI6Dfu02WM6rj6tSMzTKavpEAmXSap8BDJzNax4ZunjMkP1liqxevkWo4Zs8M0gOvKQmPrQIHPBssOVDUlY0TCc/Fn1Xf220M7sAdSt+mpOdVZGI5/VxWqUeJYy+GZDWjDJ3qmmP7RvP2YWlohPpNN7RN3X03NckBRLGrPYRgNttTzEigODdfAhq0tQGotW6r2GW2hBI/7bRo1zEJXohNLvHIIl5z9ci3RamOrXe2C1fay9ZELRepEF8LsbrR9JRGvPLSzmwLlxSvljvrmGaYAGabNVegpx1rub+v5gNk23IX9+eWUyGjvSoDGuWgIzxVECgYEA6j3M6v0AA3/35khf4Bmt0qRDVbxJxgb5MYXSOqjWuGOiudI/aADSKJcY8rDz5gubkTPaVgdMWmj29r5eLQ679EWf2K/f41fUazRGZ+myuj9/l7Q58WDEPssfB3DVP/4LIWQ6QSA1A7X2NKTf45B9Eb4MyqOugRposyAnUPzDDGUCgYEAlmd5XsooUdfZGvDuzRbbU+8rH+0WFwlcgWVM3XK9pakfO026RcEbGk6j51b0CVxmVEgFeYzzAId2wfJNnxYSCyZZU1drnYaoCOeWiJAC6aTU5Tiw3xXhjFKfL2eMY3r075pa+jzCSttA/F0uZoAbkbklkHZ2juTEibJKrk4Uh4UCgYAx3CHISz47gHvGGtW9n/muAqUKlN+nNUjJz9BmCBZcfWjf4O76NmKFnVQEJMJlz0a366+n7DnGbN1UvETTlnVPk5pox1cCz2k5wJDUAZy3pFiGdCh5Rr2/GAFs1gmua2b3Hpx/zFk8hvj3T7kQeWsF4cxbPeghNvveVRPJW2QxOQKBgBJh7zmgp7DpGsXqMKWsZ34ouzKZvZtvL3k5Ml3WiktXElQjOeMQqQlcFzhNLmJ+gptGejTS/1hPNjqaLNaG0gm+1CgVhTepn5wHAiUKxPBdjw+9EBEUEY8fAgm/NC9sdcdbLEdtaanQhm7RzLwGaFg1MtwnPnJUj5jsy6fmLygpAoGBAOZIfG+EY9Srk1tpH1JpXos3M89qJbAtRcT5F99Q36/xHfVB22O2AbWJTcRMeBed34HyN2oesAY/VNsV7R36b1cxsNmWZByaKxN1/F76L4wXY+bNOJAAs3rQ46pStmyWPoZ9Y0G2yk9sIsg+XN6vR4GIVr2im6TcfiGwbq7SXY/Z
-----END RSA PRIVATE KEY-----''',
    'alipay_public_key_string': '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApTuB5tkO49Wk/a81P7AIJHNXWssg9FdrjrdDUPB2WYb4N4sAxk7E4nH37UExcTTqQ2cBixokLxS1fwtZszUhpwVbS/OPs3Gme14QvFI86WmjL9LMKNumVg4rQkQslEKJmg/5mqq7QX9g0W+IpAntS5OZs+Oc79xDTphBVXinZqFk9/T5iz4JoqVyRpw/4QDa8t5W3qWhk6vPGpbJPJShpuLyWdhfAU4uxKa1WEPu2xWA+4ciokq0NgTgW/VGV5nWO6kbwlxq1V2snldhOs1bHZy3VbKTWbAiPAb6dDPXu9ryh3b+GrbnmNIjLKODjT4rYAnuS4RGj25hw/Sh4HM8TQIDAQAB
-----END PUBLIC KEY-----''',
    'sign_type': 'RSA2',
    'debug': True           # true开发测试,false生产环境
}





# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'orderapp': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



# 跨域白名单：允许 Vue 后台域名访问（开发环境）
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://127.0.0.1:8080,http://localhost:8080').split(',')
CORS_ORIGIN_WHITELIST = CORS_ALLOWED_ORIGINS 

# 允许跨域携带 Cookie（关键！Django 会话认证需要）
CORS_ALLOW_CREDENTIALS = True



# DRF配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # 移除或注释掉SessionAuthentication
        # 'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



# 缓存配置(首页每日热门商品缓存)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

