# Generated by Django 5.2 on 2025-11-04 02:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="可选的用户名",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="用户登录密码", max_length=128, verbose_name="密码"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="用户的主要邮箱地址，用于登录",
                        max_length=254,
                        unique=True,
                        verbose_name="邮箱地址",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="用户个人手机号码，与收件地址手机号码不同",
                        max_length=15,
                        null=True,
                        verbose_name="个人手机号",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="users/avatars/default.png",
                        help_text="用户头像图片",
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="用户昵称，最多30字",
                        max_length=30,
                        verbose_name="昵称",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女")],
                        help_text="用户的性别",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="用户的出生日期", null=True, verbose_name="出生日期"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="用户个人简介，最多500字",
                        max_length=500,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, help_text="标识用户的邮箱是否已验证", verbose_name="邮箱已验证"
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, help_text="标识用户的手机号是否已验证", verbose_name="手机号已验证"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "custom_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_name", models.CharField(max_length=50, verbose_name="收货人")),
                (
                    "receiver_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区县")),
                (
                    "detail_address",
                    models.CharField(max_length=200, verbose_name="详细地址"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认地址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收货地址",
                "verbose_name_plural": "收货地址",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="custom_user_email_55dec9_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="custom_user_usernam_674d82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="custom_user_phone_e281b2_idx"),
        ),
    ]
